### ISSUE TITLE
Raise expection if stamp image is not found, similar to logo 

### ISSUE THREAD

**Issue by strzibny** [strzibny/invoice_printer#16]
```
$ ruby pokus.rb
/home/strzibny/.gem/ruby/gems/invoice_printer-1.0.0.rc1/lib/invoice_printer/pdf_document.rb:74:in `initialize': Logotype file not found at prawn.png (InvoicePrinter::PDFDocument::LogoFileNotFound)
	from /home/strzibny/.gem/ruby/gems/invoice_printer-1.0.0.rc1/lib/invoice_printer.rb:66:in `new'
	from /home/strzibny/.gem/ruby/gems/invoice_printer-1.0.0.rc1/lib/invoice_printer.rb:66:in `print'
	from pokus.rb:59:in `<main>'

$ ruby pokus.rb
/home/strzibny/.gem/ruby/gems/prawn-2.1.0/lib/prawn/images.rb:142:in `verify_and_open_image': stamp.png not found (ArgumentError)
```

**Comment by 3minus1** [comment]
Can be closed.
